### ISSUE TITLE
extra open parentheses on presentation link 

### ISSUE THREAD

**Issue by rlisinker** [laser-umn/laser-umn.github.io#1]
https://github.com/laser-umn/laser-umn.github.io/blob/6834d777ed2f179e05f87423697e51d4bfe3fcaa/publications.qmd#L59C117-L59C127

link for Legacy, C., Zieffler, A., Fry, E., & Le, L. (2020, February) under presentations isn't working because of extra open parentheses

**Comment by calegacy** [comment]
updated!
